# Rename to docker-compose.yml
# play with HYPRIOT-OS-32bits : https://blog.hypriot.com/downloads/
# Flash microSD with etcher: https://etcher.io/
# MAINTAINER Julien Ancelin <julien.ancelin@inra.fr>
version: '3.2'
services:
   mosquitto:
     image: fstehle/rpi-mosquitto
     restart: always
     ports:
      - 1883:1883

   grafana:
     image: tcjennings/rpi-grafana
     restart: always
     ports:
      - 3000:3000

#   influxdb:
#     image: influxdb
#     restart: always
#     ports:
#      - 8086:8086

